import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { checkout } from '../checkout';
import ResponsiveAppBar from '../components/ResponsiveAppBar';
import MyCanvas from '../components/HomePage/MyCanvas/MyCanvas';
import styled from 'styled-components';
import getHomepageScene from '../components/HomePage/MyCanvas/HomepageScene/getHomepageScene';
import cl from '../colors';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trig Tutor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/trig_tutor_logo.svg" />
      </Head>
      <Wrapper>
        <ResponsiveAppBar />

        <TopSection>
          <h2> Get Good At Trig.</h2>
          <MyCanvas sceneGetter={getHomepageScene} />
          <h2>
            {' '}
            Really, <RainbowText>Really</RainbowText> Good.
          </h2>
        </TopSection>
        <BottomSection></BottomSection>
      </Wrapper>

      {/* <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>testd in-depth information about Next.js features and API.</p>
          </div>

          <div href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </div>

          <div
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </div>

          <div
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </div>

          <button
            onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: 'price_1LbGYmAu4BvCeixjrZOKg0vT',
                    quantity: 1,
                  },
                  {
                    price: 'price_1LflrqAu4BvCeixjRGXph4oG',
                    quantity: 1,
                  },
                ],
              });
            }}
          >
            buy
          </button>
        </div> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/trig_tutor_logo.svg"
              alt="trig tutor Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}

const Wrapper = styled.div`
  display: flex;
  flex-flow: column;
  min-height: 100vh;
`;

const TopSection = styled.div`
  /* background: linear-gradient(
    -120deg,
    hsl(190, 100%, 85%) 10%,
    hsl(190, 100%, 40%),
    hsl(225, 72%, 60%) 50%,
    hsl(340, 90%, 50%) 90%
  ); */
  background-color: white;

  background-size: 150%;
  background-position-x: 50%;
  background-position-y: 50%;
  height: 390px;
  width: 100%;
  display: flex;
  align-items: center;
  flex-direction: column;
`;

const BottomSection = styled.div`
  background: linear-gradient(
    -120deg,
    ${cl.getHSL(cl.blue_light)} 10%,
    ${cl.getHSL(cl.blue)},
    ${cl.getHSL(cl.purple)} 50%,
    ${cl.getHSL(cl.red)} 90%
  );
  /* background-color: white; */
  background-size: 180%;
  background-position-x: 50%;
  background-position-y: 50%;
  flex: 1;
`;

const RainbowText = styled.div`
  background: linear-gradient(
    90deg,
    ${cl.getHSL(cl.blue)},
    ${cl.getHSL(cl.purple)},
    ${cl.getHSL(cl.red)}
  );

  background-size: 100%;
  color: transparent;
  -webkit-background-clip: text;
  -moz-background-clip: text;
  -webkit-text-fill-color: transparent;
  -moz-text-fill-color: transparent;
`;
